/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package me.jbduncan.adventofcode2022.day3;

import static com.google.common.truth.Truth.assertThat;

import java.io.IOException;
import java.io.PrintWriter;
import java.io.StringWriter;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Arrays;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

class AppTests {

  private static Path tempFile(String contents) throws IOException {
    var tempFile = Files.createTempFile("", "");
    Files.writeString(tempFile, contents);
    return tempFile;
  }

  private static String executeAndReturnStdOut(Object... args) throws IOException {
    var out = new StringWriter();
    App.execute(Arrays.stream(args).map(Object::toString).toList(), new PrintWriter(out, true));
    return out.toString().strip();
  }

  @Nested
  class GivenStar5Input {

    @Nested
    class WhenRunningApp {

      @Test
      void thenItReturns157() throws IOException {
        var tempFile =
            tempFile(
                """
                vJrwpWtwJgWrhcsFMMfFFhFp
                jqHRNqRjqzjGDLGLrsFMfFZSrLrFZsSL
                PmmdzqPrVvPwwTWBwg
                wMqvLMZHhHMvwLHjbvcjnnSBnvTQFn
                ttgJtRGJQctTZtZT
                CrZsJsPPZsGzwwsLwLmpwMDw
                """);
        var out = executeAndReturnStdOut(tempFile);
        assertThat(out).isEqualTo("157");
      }
    }
  }

  @Nested
  class GivenStar6Input {

    @Nested
    class WhenRunningApp {

      @Test
      void thenItReturns70() throws IOException {
        var tempFile =
            tempFile(
                """
                vJrwpWtwJgWrhcsFMMfFFhFp
                jqHRNqRjqzjGDLGLrsFMfFZSrLrFZsSL
                PmmdzqPrVvPwwTWBwg
                wMqvLMZHhHMvwLHjbvcjnnSBnvTQFn
                ttgJtRGJQctTZtZT
                CrZsJsPPZsGzwwsLwLmpwMDw
                """);
        var out = executeAndReturnStdOut(tempFile, "--elf-trios");
        assertThat(out).isEqualTo("70");
      }
    }
  }
}
